/**
 * sendSmsPrayer.ts
 * Server-only — sends a nightly prayer via Twilio SMS.
 * Never import this from client components.
 */

import twilio from "twilio";

export interface SendSmsPrayerInput {
  to:          string;
  firstName:   string;
  prayerText:  string;
}

export interface SendSmsPrayerResult {
  messageSid: string;
  smsText:    string;
}

/**
 * Assembles the final SMS string from a short prayer text.
 * The prayer should already be ~35 words (generated by generateSmsPrayer).
 * A safety trim is applied if it somehow exceeds the 280-char total budget.
 */
function buildSmsText(firstName: string, prayerText: string): string {
  const header = `Tonight's prayer for ${firstName}: `;
  const footer = `\n— My Nightly Prayer\nReply STOP to opt out.`;
  const budget = 280 - header.length - footer.length;

  let prayer = prayerText.trim();
  if (prayer.length > budget) {
    prayer = prayer.slice(0, budget).trimEnd() + "…";
  }

  return `${header}${prayer}${footer}`;
}

export async function sendSmsPrayer(input: SendSmsPrayerInput): Promise<SendSmsPrayerResult> {
  const { to, firstName, prayerText } = input;

  const accountSid = process.env.TWILIO_ACCOUNT_SID;
  const authToken  = process.env.TWILIO_AUTH_TOKEN;
  const fromNumber = process.env.TWILIO_PHONE_NUMBER;

  if (!accountSid || !authToken || !fromNumber) {
    throw new Error(
      "[sendSmsPrayer] Missing Twilio env vars. Required: TWILIO_ACCOUNT_SID, TWILIO_AUTH_TOKEN, TWILIO_PHONE_NUMBER",
    );
  }

  const smsText = buildSmsText(firstName, prayerText);
  const client  = twilio(accountSid, authToken);

  const message = await client.messages.create({
    body: smsText,
    from: fromNumber,
    to,
  });

  console.log(`[sendSmsPrayer] Sent to ${to} — SID: ${message.sid}`);
  return { messageSid: message.sid, smsText };
}
